### ISSUE TITLE
It would be nice add the currentCommitID to the request itself

### ISSUE THREAD

**Issue by piotrbrzo** [FTS-Group/Complete#6]
In the ```sendRequestToServer()``` function it would be nicer if we managed to somehow insert the ```currentCommitID``` into ```req```.
Currently I am emitting it, saving to the ```nextCommitID``` variable and if the replica becomes the Coordinator moving it into ```currentCommitID```.
It could also break if the messages are not delivered in order.
It is beneficial to have the ID on the Gateway - it helps with the termination protocol.

**Comment by radubl** [comment]
couldn't do it. adding the ccID to the req object works locally, but once sent over the network it somehow gets reset.
